package mapper;

import entity.UserSample;
import entity.UserSampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    long countByExample(UserSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int deleteByExample(UserSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int insert(UserSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int insertSelective(UserSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    List<UserSample> selectByExample(UserSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    UserSample selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int updateByExampleSelective(@Param("record") UserSample record, @Param("example") UserSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int updateByExample(@Param("record") UserSample record, @Param("example") UserSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int updateByPrimaryKeySelective(UserSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sample
     *
     * @mbg.generated Sun Dec 27 22:09:07 JST 2020
     */
    int updateByPrimaryKey(UserSample record);
}