package entity;

public class UserSample {

	public UserSample() {

	}

	/**
	 * @param id
	 * @param name
	 * @param password
	 */
	public UserSample(String id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_sample.ID
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_sample.NAME
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_sample.PASSWORD
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_sample.ID
	 *
	 * @return the value of user_sample.ID
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_sample.ID
	 *
	 * @param id the value for user_sample.ID
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_sample.NAME
	 *
	 * @return the value of user_sample.NAME
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_sample.NAME
	 *
	 * @param name the value for user_sample.NAME
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_sample.PASSWORD
	 *
	 * @return the value of user_sample.PASSWORD
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_sample.PASSWORD
	 *
	 * @param password the value for user_sample.PASSWORD
	 *
	 * @mbg.generated Sun Dec 27 22:09:07 JST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
}